### PR TITLE
Bugfix: Setting proper object for reading a key file

### PR DESCRIPTION
**Pull request by cardil**

### CODE REVIEW

**Comment by blaa** [comment]
Merci beacoup! (I've recently got back to writting Rust version of baryssh)

**Comment by cardil** [comment]
Any chances on bugfix release on PyPI?

**Comment by blaa** [comment]
Yes. Will do it today. 

On 1 March 2018 09:46:18 CET, "Krzysztof Suszyński" <notifications@github.com> wrote:
>Any chances on bugfix release on PyPI?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/blaa/barySSH/pull/6#issuecomment-369518100

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blaa** [comment]
Check it out.

On 1 March 2018 09:46:18 CET, "Krzysztof Suszyński" <notifications@github.com> wrote:
>Any chances on bugfix release on PyPI?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/blaa/barySSH/pull/6#issuecomment-369518100

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cardil** [comment]
Thx!

**Pull request merged**
